export type TTypographyTypes =
    | 'displayLarge'
    | 'displayMedium'
    | 'displaySmall'
    | 'headlineMedium'
    | 'headlineSmall'
    | 'bodyLarge'
    | 'bodyMedium'
    | 'bodySmall'
    | 'bodyAccentLarge'
    | 'bodyAccentMedium'
    | 'bodyAccentSmall'
    | 'caption'
    | 'captionAccent'
